# Generated by Django 6.0 on 2026-01-13 14:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField(default="Je joue à 'Spyfall'. Génère un mot secret en Français appartenant à cette catégorie : '{category}'. Sois imaginatif. Réponds UNIQUEMENT par le mot, sans article ni ponctuation.", help_text='Use {category} where you want the random category to appear.')),
                ('categories', models.TextField(default='Un objet du quotidien\nUn animal\nUn métier\nUn personnage célèbre\nUn lieu', help_text='Put each category on a new line.')),
                ('kalak_prompt', models.TextField(default='Donne-moi une question de culture générale obscure et sa réponse.')),
            ],
        ),
        migrations.CreateModel(
            name='KalakConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='Donne-moi UNE question de culture générale très surprenante sur le thème : {theme}. La réponse doit être courte (1 à 4 mots max). Réponds UNIQUEMENT avec ce format : QUESTION|RÉPONSE', help_text='Use {theme} where you want the random category to appear.')),
                ('categories', models.TextField(default="les animaux étranges, l'histoire, l'espace, le corps humain, les pirates, le cinéma")),
                ('model', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('max_rounds', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=core.models.generate_room_code, max_length=6, unique=True)),
                ('current_game', models.CharField(choices=[('SPY', 'Spy Game'), ('KALAK', 'Kalak')], default='SPY', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_word', models.CharField(blank=True, max_length=100)),
                ('is_voting', models.BooleanField(default=False)),
                ('kalak_question', models.TextField(blank=True)),
                ('kalak_real_answer', models.CharField(blank=True, max_length=200)),
                ('kalak_round', models.IntegerField(default=0)),
                ('kalak_image_url', models.URLField(blank=True, null=True)),
                ('kalak_phase', models.CharField(default='WRITING', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('confirmed_players', models.ManyToManyField(blank=True, related_name='confirmed_games', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='joined_games', to=settings.AUTH_USER_MODEL)),
                ('round_players', models.ManyToManyField(blank=True, related_name='finished_step', to=settings.AUTH_USER_MODEL)),
                ('spy_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spy_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KalakBluff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_bluffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='core.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
