# Generated by Django 6.0 on 2026-01-13 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready_players',
            field=models.ManyToManyField(blank=True, related_name='ready_in_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
