# Generated by Django 6.0 on 2025-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField(default="Je joue à 'Spyfall'. Génère un mot secret en Français appartenant à cette catégorie : '{category}'. Sois imaginatif. Réponds UNIQUEMENT par le mot, sans article ni ponctuation.", help_text='Use {category} where you want the random category to appear.')),
                ('categories', models.TextField(default='Un objet du quotidien\nUn animal\nUn métier\nUn personnage célèbre\nUn lieu', help_text='Put each category on a new line.')),
            ],
        ),
    ]
