# Generated by Django 5.0.2 on 2025-12-22 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gameconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='confirmed_players',
            field=models.ManyToManyField(blank=True, related_name='confirmed_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='current_game',
            field=models.CharField(choices=[('SPY', 'Spy Game'), ('KALAK', 'Kalak')], default='SPY', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='is_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='kalak_phase',
            field=models.CharField(default='WRITING', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='kalak_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='kalak_real_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='kalak_prompt',
            field=models.TextField(default='Donne-moi une question de culture générale obscure et sa réponse.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='spy_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spy_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='KalakBluff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_bluffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
