# Generated by Django 6.0 on 2025-12-25 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_game_id_alter_gameconfig_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kalak_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='round_players',
            field=models.ManyToManyField(blank=True, related_name='finished_step', to=settings.AUTH_USER_MODEL),
        ),
    ]
