# Generated by Django 6.0 on 2025-12-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_kalak_round_game_round_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalakConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='Donne-moi UNE question de culture générale très surprenante sur le thème : {theme}. La réponse doit être courte (1 à 4 mots max). Réponds UNIQUEMENT avec ce format : QUESTION|RÉPONSE', help_text='Use {theme} where you want the random category to appear.')),
                ('categories', models.TextField(default="les animaux étranges, l'histoire, l'espace, le corps humain, les pirates, le cinéma")),
            ],
        ),
    ]
