# Generated by Django 6.0 on 2026-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kalakconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
