# Generated by Django 6.0 on 2026-01-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_playerscore_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kalak_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
